# config.yaml

image_processing:
  hf_noise_gaussian_kernel: [3, 3]
  hf_noise_gaussian_sigma: 1

  sky_gaussian_kernel: [125, 125]
  sky_gaussian_sigma: 125

  hsv_lower_bound: [0, 0, 0]    # (hb, sb, vb)
  hsv_upper_bound: [180, 255, 255]  # (ht, st, vt)

  adaptive_threshold_max_value: 255
  adaptive_threshold_block_size: 5
  adaptive_threshold_constant: 4

  sobel_pre_gaussian_kernel: [3, 3]
  sobel_pre_gaussian_sigma: 0.5

  sobel_x_kernel: 3
  sobel_y_kernel: 3
  sobel_threshold: 50

# Example RL parameters (optional)
rl:
  learning_rate: 0.0001
  gamma: 0.99
  episodes: 500
