# config.yaml

#(108, 76, 188)
#Upper Bound: (112, 107, 242)

image_processing:
  hf_noise_gaussian_kernel: [3, 3]
  hf_noise_gaussian_sigma: 1

  sky_gaussian_kernel: [125, 125]
  sky_gaussian_sigma: 125

  #make maximal bounds - all  255
  #hsv_lower_bound: [0, 0, 0]    
  #hsv_upper_bound: [180, 255, 255] 
  hsv_lower_bound: [100, 40, 133]    # (hb, sb, vb)
  hsv_upper_bound: [170, 159, 255]  # (ht, st, vt)


  adaptive_threshold_max_value: 255
  adaptive_threshold_block_size: 5
  adaptive_threshold_constant: 4

  sobel_pre_gaussian_kernel: [3, 3]
  sobel_pre_gaussian_sigma: 0.5

  sobel_x_kernel: 3
  sobel_y_kernel: 3
  sobel_threshold: 50

  object_area_threshold: 400

# Example RL parameters (optional)
rl:
  learning_rate: 0.0001
  gamma: 0.99
  episodes: 500
